# Generated by Django 5.1.1 on 2024-10-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
