# Generated by Django 5.1.1 on 2024-10-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appt_status',
            field=models.BooleanField(default=False),
        ),
    ]
